package com.vzap.trytons.enums;

public enum SystemReportType {
    ACTIVE_USERS,
    ACTIVE_LEAGUES,
    TOP_FANTASY_TEAMS,
    TOP_RUGBY_PLAYERS,
    MOST_SELECTED_PLAYERS,
    UNAVAILABLE_PLAYERS,
    COMPLETED_FIXTURES,
    FIXTURE_RESULTS,
    TRANSFER_ACTIVITY,
    LEAGUE_CHAT_ACTIVITY,
    SYSTEM_ACTIVITY
}
